FROM backend-develop-image

COPY ./workspace /workspace

WORKDIR /workspace/cs5351-code-analysis-svc

# RUN npm install -g npm@latest
RUN npm install -g pnpm
RUN pnpm install 
# RUN npm install --no-audit

CMD ["pnpm", "run", "start"]
